bricks:
  - metaData:
      name: AppConfig
      TypeID: ConfigCenter
    lives:
      - liveID: ConfigCenter
        config:
          app_name: "My Awesome App"
          api_key: "${API_KEY}"
  - metaData:
      name: CacheConfig
      TypeID: CacheService
    lives:
      - liveID: CacheService
        config:
          cache_enabled: "true"
          cache_type: "memory"
