bricks:
  - metaData:
      name: mysql
      TypeID: Database
    lives:
      - liveID: mysql_db
        config:
          host: "${MYSQL_HOST}"
          port: 3306
          user: "${MYSQL_USER}"
          password: "${MYSQL_PASSWORD}"
          database: "mydb"
  - metaData:
    name: user service
    TypeID: UserService
  lives:
    - liveID: UserService
  - metaData:
    name: product service
    TypeID: ProductService
  lives:
    - liveID: ProductService